gallery/urls.py
from django.urls import path
from . import views

app_name = 'gallery'

urlpatterns = [
    path('list', views.PostList.as_view(), name='list'),
    path('', views.PostList.as_view(), name='list'),
    path('new/', views.PostCreate.as_view(), name='create'),
    path('<int:pk>/', views.PostDetail.as_view(), name='detail'),
    path('<int:pk>/delete', views.PostDelete,name='delete'),
    path('search_data', views.search_view, name='search'),

]

image_gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gallery/', include('gallery.urls')),
    path('', include('gallery.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):

    category = models.CharField(max_length=20)
    date=models.DateField(auto_now=True)

    def get_absolute_url(self):
        return reverse('gallery:detail', kwargs={'pk':self.pk})


class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = models.ImageField()

gallery/forms.py
from django import forms
from .models import Post, Image
from django.forms import inlineformset_factory


class ImageForm(forms.ModelForm):
    file = forms.ImageField()

    class Meta:
        model = Image
        fields = ['file', ]


ImageFormSet = inlineformset_factory(Post, Image, form=ImageForm, extra=3)

gallery/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, DeleteView
from .models import Post, Image
from .forms import ImageForm, ImageFormSet
from django.db import transaction
from django.http.response import HttpResponse


class PostList(ListView):
    model = Post
    context_object_name = 'gallery'


class PostCreate(CreateView):
    model = Post
    fields = ['category', ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['image_formset'] = ImageFormSet()
        return context

    def form_valid(self, form):
        image_formset = ImageFormSet(self.request.POST, self.request.FILES)
        with transaction.atomic():
            self.object = form.save()

            if image_formset.is_valid():
                image_formset.instance = self.object
                image_formset.save()
        return super().form_valid(form)


class PostDetail(DetailView):
    model = Post




def PostDelete(request,pk):
    po = Post.objects.filter(id = pk)
    po.delete()
    dat = Post.objects.all()
    return render(request,'gallery/post_confirm_delete.html',{'dat':dat})



def search_view(request):
    if request.method == 'GET':
        search_query = request.GET.get('search_box', None)

        fdata = Post.objects.filter(category=search_query)

        if len(fdata) != 0:

            return render(request, 'gallery/post-search.html', {'data': fdata})
        else:
            return HttpResponse('Not Found')

templates/base.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

</head>
<body>
<div id="header">



    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'gallery:list' %}">Image Gellery</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'gallery:list' %}">Gallery <span class="sr-only">(current)</span></a>
      </li>







    </ul>

  </div>

      <form type="get" action="{% url 'gallery:search' %}"  style="margin: 0">
    <input  id="search_box" type="text" name="search_box"  placeholder="Search..." >
    <button id="search_submit" type="submit" >Submit</button>
</form>




</nav>
</nav>



</div>
<div id="content">
{% block content %}
{% endblock %}
</div>
</body>
</html>

templates/gallery/post-search.html
{% extends 'base.html' %}
{% block content %}
<p>Click Here For <a href="{% url 'gallery:list' %}">Home</a> Page</p>

{% for i in data %}
    <li><a href="{% url 'gallery:detail' i.pk %}">{{ i.category }}</a></li>
{% endfor %}

{% endblock %}

templates/gallery/post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<p>Click Here For <a href="{% url 'gallery:list' %}">Home</a> Page</p>

  {% for post in dat %}
    <li><a href="{% url 'gallery:detail' post.pk %}">{{ post.category }}</a></li>
  <a href="{% url 'gallery:delete' post.pk %}">Delete</a>
  {% endfor %}



{% endblock %}

templates/gallery/post_detail.html
{% extends 'base.html' %}
{% block content %}
<p>Click Here For <a href="{% url 'gallery:list' %}">Home</a> Page</p>

<h1>{{ post.category }}</h1>

<ul>
  {% for image in post.image_set.all %}
    <li><img src="{{ image.file.url }}" alt="" width="460" height="345"></li>
  {% endfor %}
</ul>
<a href="{% url 'gallery:list' %}">Home</a>

{% endblock %}

templates/gallery/post_form.html
{% extends 'base.html' %}
{% block content %}
<p>Click Here For <a href="{% url 'gallery:list' %}">Home</a> Page</p>


<h1>Post Create</h1>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  {{ image_formset.as_p }}
  <input type="submit" value="Submit">
</form>


{% endblock %}

templates/gallery/post_list.html
{% extends 'base.html' %}
{% block content %}
{% if gallery %}
<p>
  <a href="{% url 'gallery:create' %}">New</a>
</p>
<p>Click Here For <a href="{% url 'gallery:list' %}">Home</a> Page</p>


  {% for post in gallery %}
    <li><a href="{% url 'gallery:detail' post.pk %}">{{ post.category }}</a></li>
  <a href="{% url 'gallery:delete' post.pk %}">Delete</a>
  {% endfor %}

{% else %}
<p>There is No Images, If You want to upload any images <a href="{% url 'gallery:create' %}"> click here</a> </p>
{% endif %}

{% endblock %}